import { z } from 'zod';
import { ICON_NAMES } from '../engine/assets/icons';
import { TECHNIQUES } from '../engine/techniques';
import { DISPLAY_NAMES, MONO_NAMES, SERIF_NAMES } from '../plan/fonts';
import { PlanSchema, TRANSITIONS } from '../plan/schema';

type JSONSchema = { type?: string | string[]; properties?: Record<string, JSONSchema>; required?: string[]; description?: string; default?: unknown; enum?: unknown[]; items?: JSONSchema; minItems?: number; maxItems?: number; minimum?: number; maximum?: number; minLength?: number; maxLength?: number; anyOf?: JSONSchema[]; prefixItems?: JSONSchema[] };

const schemaOf = (s: z.ZodType): JSONSchema => z.toJSONSchema(s, { io: 'input', unrepresentable: 'any' }) as JSONSchema;

/** Everything a planner (human or model) needs, as data. */
export function catalogJson() {
  return {
    version: 1,
    planSchema: schemaOf(PlanSchema),
    transitions: TRANSITIONS,
    genres: ['afro-house', 'electro'],
    fonts: { display: DISPLAY_NAMES, serif: SERIF_NAMES, mono: MONO_NAMES },
    icons: ICON_NAMES,
    techniques: TECHNIQUES.map(t => ({
      id: t.id, title: t.title, category: t.category, summary: t.summary, guidance: t.guidance ?? '',
      beats: t.beats, energy: t.energy, params: schemaOf(t.params), example: t.example,
    })),
  };
}

function typeOf(s: JSONSchema): string {
  if (s.enum) return s.enum.map(v => JSON.stringify(v)).join(' | ');
  if (s.anyOf) return s.anyOf.map(typeOf).join(' | ');
  if (s.type === 'array') {
    if (s.prefixItems) return `[${s.prefixItems.map(typeOf).join(', ')}]`;
    const n = s.minItems !== undefined || s.maxItems !== undefined ? ` (${s.minItems ?? 0}–${s.maxItems ?? '∞'})` : '';
    return `${s.items ? typeOf(s.items) : 'any'}[]${n}`;
  }
  if (s.type === 'object' && s.properties) return `{ ${Object.entries(s.properties).map(([k, v]) => `${k}${s.required?.includes(k) ? '' : '?'}: ${typeOf(v)}`).join('; ')} }`;
  const lim = s.maxLength !== undefined ? ` ≤${s.maxLength}` : s.minimum !== undefined || s.maximum !== undefined ? ` ${s.minimum ?? ''}..${s.maximum ?? ''}` : '';
  return `${Array.isArray(s.type) ? s.type.join('|') : s.type ?? 'any'}${lim}`;
}

export function catalogMarkdown(): string {
  const c = catalogJson();
  const out: string[] = [
    '# Technique catalog',
    '',
    '> Generated by `motion catalog --md` from the technique source code. Do not edit by hand.',
    '',
    `Transitions: ${c.transitions.map(t => `\`${t}\``).join(', ')} · Genres: ${c.genres.map(g => `\`${g}\``).join(', ')}`,
    '',
    `Display fonts: ${c.fonts.display.join(', ')} · Serif: ${c.fonts.serif.join(', ')} · Mono: ${c.fonts.mono.join(', ')}`,
    '',
    `Particle icons: ${c.icons.map(i => `\`${i}\``).join(', ')}`,
    '',
  ];
  for (const cat of ['intro', 'type', 'ui', 'shape', 'camera', 'data', 'brand', 'outro']) {
    const list = c.techniques.filter(t => t.category === cat);
    if (!list.length) continue;
    out.push(`## ${cat[0].toUpperCase()}${cat.slice(1)}`, '');
    for (const t of list) {
      const b = t.beats.min === t.beats.max ? `exactly ${t.beats.min}` : `${t.beats.min}–${t.beats.max}, default ${t.beats.default}`;
      out.push(`### \`${t.id}\` — ${t.title}`, '', `*Beats: ${b} · default energy ${t.energy}*`, '', t.summary, '');
      if (t.guidance) out.push(`**Guidance:** ${t.guidance}`, '');
      const props = Object.entries(t.params.properties ?? {});
      if (props.length) {
        out.push('| param | type | default | notes |', '|---|---|---|---|');
        for (const [k, v] of props) {
          const req = t.params.required?.includes(k) && v.default === undefined;
          out.push(`| \`${k}\`${req ? ' *' : ''} | ${typeOf(v).replace(/\|/g, '\\|')} | ${v.default !== undefined ? `\`${JSON.stringify(v.default)}\`` : ''} | ${v.description ?? ''} |`);
        }
        out.push('');
      } else out.push('No params.', '');
      out.push('```json', JSON.stringify({ technique: t.id, beats: t.beats.default, params: t.example }, null, 2), '```', '');
    }
  }
  return out.join('\n');
}
